// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { IndexGetData, IndexGetResponses, VideoFeedVideoFeedGetData, VideoFeedVideoFeedGetResponses, SnapshotSnapshotGetData, SnapshotSnapshotGetResponses, CameraStatusCameraStatusGetData, CameraStatusCameraStatusGetResponses, CameraDebugCameraDebugGetData, CameraDebugCameraDebugGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Index
 */
export const indexGet = <ThrowOnError extends boolean = false>(options?: Options<IndexGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<IndexGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/',
        ...options
    });
};

/**
 * Video Feed
 */
export const videoFeedVideoFeedGet = <ThrowOnError extends boolean = false>(options?: Options<VideoFeedVideoFeedGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<VideoFeedVideoFeedGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/video_feed',
        ...options
    });
};

/**
 * Snapshot
 */
export const snapshotSnapshotGet = <ThrowOnError extends boolean = false>(options?: Options<SnapshotSnapshotGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<SnapshotSnapshotGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/snapshot',
        ...options
    });
};

/**
 * Camera Status
 */
export const cameraStatusCameraStatusGet = <ThrowOnError extends boolean = false>(options?: Options<CameraStatusCameraStatusGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<CameraStatusCameraStatusGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/camera/status',
        ...options
    });
};

/**
 * Camera Debug
 */
export const cameraDebugCameraDebugGet = <ThrowOnError extends boolean = false>(options?: Options<CameraDebugCameraDebugGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<CameraDebugCameraDebugGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/camera/debug',
        ...options
    });
};