// This file is auto-generated by @hey-api/openapi-ts

export type IndexGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type IndexGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VideoFeedVideoFeedGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/video_feed';
};

export type VideoFeedVideoFeedGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SnapshotSnapshotGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/snapshot';
};

export type SnapshotSnapshotGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CameraStatusCameraStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/camera/status';
};

export type CameraStatusCameraStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CameraDebugCameraDebugGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/camera/debug';
};

export type CameraDebugCameraDebugGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: (string & {});
};